# Generated by Django 3.2.8 on 2021-10-14 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EcommerceApp.category'),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('BANED', 'banned'), ('ACTIVE', 'active'), ('PENDING', 'pending')], default='ACTIVE', max_length=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='classification',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='EcommerceApp.classification'),
        ),
    ]
