# Generated by Django 3.2.8 on 2021-10-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0003_auto_20211019_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('BANED', 'banned'), ('ACTIVE', 'active')], default='ACTIVE', max_length=7),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipped_date',
            field=models.DateTimeField(blank=True, default='00:00:00', null=True),
        ),
    ]
